### PR TITLE
Remove gcc/g++ warnings

### PR DESCRIPTION
**Pull request by lypnol**

### CODE REVIEW

**Comment by badouralix** [comment]
🤣 🤣 🤣

**Comment by badouralix** [comment]
Would be better to revert https://github.com/lypnol/adventofcode-2017/commit/f424cc43c8941066b13128a87318b84b50fa6228.
Imho we should keep warnings and write better code.

**Comment by lypnol** [comment]
tell that to @JulesDT 😛

**Comment by JulesDT** [comment]
I agree with @badouralix 
But I also think we shouldn't bother with additional warnings :) Just the regular ones maybe

**Comment by badouralix** [comment]
Is everyone fine with `-Wall` ?

**Comment by lypnol** [comment]
fixed [here](https://github.com/lypnol/adventofcode-2017/pull/195/commits/c397f6855f2c8aff999711e2d395f4f9aca4973d)

**Pull request closed without merging**
